### ISSUE TITLE
React has detected a change in the order of Hooks called by HeaderConfig.

### ISSUE THREAD

**Issue by erwanlpfr** [expo/router#167] opened 2022-12-24 14:46 UTC
### Summary

Hello,

I have this following error :

```
Warning: React has detected a change in the order of Hooks called by HeaderConfig. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. undefined                  useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in HeaderConfig (created by SceneView)
```

HeaderConfig comes from react-navigation.
If I follow the stack, the first "problematic" file that I use is ProfileHeaderButton.
It is called in a screen where I define un header button. 
Inside, I use a simple : `const link = useLink();`.

And I get this warning.
So, I may miss something, or it comes from another side of this lib or react-navigation lib?

Thank you!!

### Minimal reproducible example

```typescript 
# _layout.tsx
function RootLayout() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <Provider store={store}>
        <ListenerManager>
          <NativeBaseProvider>
            <Stack
              screenOptions={{
                headerTitleAlign: 'left',
                animation: 'fade',
              }}
            />
          </NativeBaseProvider>
        </ListenerManager>
      </Provider>
    </GestureHandlerRootView>
  );
}
```

```typescript
# index.tsx
function Home() {
  return (
    <>
      <Stack.Screen options={{
        title: null,
        headerTransparent: true,
        headerLeft: ProfileAndBackHeaderButton,
        headerRight: SettingsHeaderButton,
      }}
      />
      <View style={{ flex: 1 }}>
        <Map />
        <BottomSheet
          index={0}
          snapPoints={['20%']}
        >
          <TrackerModal />
        </BottomSheet>
      </View>
    </>
  );
}
```
```typescript
# ProfileHeaderButton.tsx
function ProfileHeaderButton() {
  const link = useLink();

  const onPressAction = useCallback(() => {
    link.push('/profile');
  }, [link]);

  return (
    <IconButton
      width={45}
      height={45}
      borderRadius="full"
      bgColor="white"
      onPress={onPressAction}
      icon={(
        <Feather
          name="user"
          size={20}
          color="black"
        />
      )}
    />
  );
}
```

**Comment by EvanBacon** [comment] 2023-06-29 20:20
Closing as we cannot fix in this repo

**Closed by EvanBacon** 2023-06-29 20:20 UTC
Labels: React Navigation, external

**Comment by balloman** [comment] 2023-06-30 16:12
@erwanlpfr Did you ever find a fix? Tried switching to expo router and dealing with this issue right now, doesn't seem possible to use hooks in headers at the moment.

**Comment by erwanlpfr** [comment] 2023-06-30 16:45
No, unfortunately!
But since I started new projects and waiting for the V2 I didn't take time to find any workaround !
Let us know if you find it !

**Comment by balloman** [comment] 2023-06-30 16:53
It seems I was able to find a workaround by configuring all header options in layout instead of in the base component. It's unfortunate because now there wouldn't be a way to pass information to the header component but this seems to be at the very least consistent with React Navigation so

**Comment by balloman** [comment] 2023-06-30 16:54
@EvanBacon Is this expected behavior?

**Comment by ludwig-pro** [comment] 2023-09-22 10:05
👋 ! 

You should use a function cf: https://reactnavigation.org/docs/elements/#headerleft 

```jsx
      <Stack.Screen
        options={{
          header: () => <Header />, //  ✅
        }}
      />
``` 

```jsx
      <Stack.Screen
        options={{
          header: Header, //  ❌
        }}
      />
```
