### ISSUE TITLE
Uncaught Error: Higher priority Layout Route "./_layout.tsx" overriding redundant Layout Route "./_layout". Remove the Layout Route "./_layout" to fix this.

### ISSUE THREAD

**Issue by madsbuch** [expo/router#283] opened 2023-02-14 14:43 UTC
### Summary

Expo Router throws a meaningless error: Uncaught Error: Higher priority Layout Route "./_layout.tsx" overriding redundant Layout Route "./_layout". Remove the Layout Route "./_layout" to fix this.

It fixed to rename the `layout.tsx` to `layout.js`; however, It would appear to be a bug not being able to use typescript for layout files.

Making this change also unlocked another bug:

```
Uncaught Error: Using deprecated Layout Route format: Move `./app/(rounds)./(rounds)` to `./app/(rounds)/_layout./(rounds)`
```

I have a layout in the root of the `./app` folder, which seems to be congruent with what the demo app suggests doing. Also the error is not recording my folder structure which is as the following screenshot.

<img width="148" alt="Screenshot 2023-02-14 at 14 42 49" src="https://user-images.githubusercontent.com/1612807/218770806-bba00195-719e-43ef-9ac1-beca8b1b6d43.png">

I hope to have these bugs recorded!

### Minimal reproducible example

,

**Comment by EvanBacon** [comment] 2023-02-14 17:27
Seems like a minor issue with Metro which causes the module to update with both `_layout.js` and `_layout.tsx` for a tick, then updates correctly. You cannot have two files with the same name but different extensions.

**Comment by madsbuch** [comment] 2023-02-14 18:16
I have never had more than a single `layout.xxx` file in the repo. It uses the same structure as the demo app, which baffles me.

I also only have this problem on web. The app runs smoothly in the ios simulator. To me, this indicates a bug with webpack or the like in the web stack.

I read through https://github.com/expo/router/blob/e2a41d72ddafb4261b9c624411d0014eabbb2494/packages/expo-router/src/getRoutes.ts to understand the error without any success.

**Comment by EvanBacon** [comment] 2023-02-14 18:21
> It fixed to rename the layout.tsx to layout.js; however, It would appear to be a bug not being able to use typescript for layout files.

During this rename watchman may have reported the changes one at a time, leading to a slight overlap which triggered the duplicate error.

> I also only have this problem on web. The app runs smoothly in the ios simulator. To me, this indicates a bug with webpack or the like in the web stack.

Expo Router doesn't use Webpack, the tooling stack is universal.

**Comment by madsbuch** [comment] 2023-02-14 18:57
I am terribly sorry about the limited reproducibility I provide in this report. I guess the best thing is to leave it be for now and wait for somebody else to also encounter the problem and, hopefully, find this issue.

**Comment by EvanBacon** [comment] 2023-02-14 23:05
thanks for the repro, I'll investigate.

**Comment by DrMisQ** [comment] 2023-02-21 05:35
same error with me (only on production) expo build:web after deploying it gives me the same exact error

note: this error does not show when call expo start, it shows only after building the web

**Comment by DrMisQ** [comment] 2023-02-21 14:01
it looks like when using (npx expo export) and deploying the dist folder this error does not show and it works fine

**Comment by EvanBacon** [comment] 2023-02-22 02:42
- Use `npx expo export` (`-p web` for web-only bundling).
- `expo build:web` is deprecated.
- `npx expo export:web` is used for Webpack (unsupported) and will eventually be deprecated in favor of the universal `npx expo export`.

**Comment by EvanBacon** [comment] 2023-05-21 16:37
Closing as I cannot repro this and therefore cannot fix. Please feel free to open with a reproducible example.

**Closed by EvanBacon** 2023-05-21 16:37 UTC
Labels: Metro, external

**Comment by RobertUpchurch** [comment] 2023-08-18 16:45
I was receiving this error because i had 2 files that were technically the same path.

for example something like this throws this error.

```
/app
/app/page.tsx
/app/page/index.tsx
```

This was my own user error 100% but the error message lead me to this thread and possibly someone else will need this helpful hint.
