### ISSUE TITLE
"Fast Refresh" and app crash on Developer Menu open in Monorepo

### ISSUE THREAD

**Issue by ShaneKeney** [expo/router#264] opened 2023-02-08 17:30 UTC
### Summary

**Background:**
I have two app project templates in the Monorepo: `expo-router-template` and `expo-monorepo-example`.  These can be found in `apps/` directory.

**Issue 1:**
"Fast Refresh" not working when `expo-router-template` project is in the Monorepo.  

Run `pnpm dev:ert` (Runs `expo-router-template`) in the root and open the app via Expo Go.  Change `index.tsx` text component.  No update occurs.
Run `pnpm dev:emt` (Runs `expo-monorepo-example`) in the root and open the app via Expk Go.  Change `index` text component.  No update occurs.
Delete `expo-router-template` and then run `pnpm dev:emt`.  Change `index` file and "Fast Refresh" functionality returns.

**Issue 2:**
Adding `app.config.js` to `expo-router-template` and attempting to open Developer Menu via 3 finger touch or "Shake to Reload" crashes app.  This is not an issue when using `app.json`.

### Minimal reproducible example

See following repo https://github.com/ShaneKeney/expo-router-monorepo-bug.

Derived and slimmed down from:  https://github.com/byCedric/expo-monorepo-example

**Comment by ShaneKeney** [comment] 2023-02-09 13:34
In reference to **Issue 2**:
I've figured out that if I remove the `runtimeVersion` field from `app.config.js`, the crashing stops.  I have to dig a bit deeper to see why that was causing the app to crash but that seems to be the source.

**Comment by EvanBacon** [comment] 2023-02-13 23:27
I don't see a `app.config.js` file in your repro. I imagine it was using `process.env.BUILD_NUMBER` or related value that Metro uses to disable Fast Refresh (i.e. not related to Expo Router). Should be fixed in SDK 48 where we overwrite the disabling https://github.com/expo/expo/pull/20939

> Issue 2

I cannot reproduce this either using the provided repo as there are no `app.config.js` files. Feel free to reopen with info that leads to a reproducible error.

I imagine this is also not related to Expo Router as it has no overlap with the features described here. Possibly some settings in the file you added.

**Closed by EvanBacon** 2023-02-13 23:27 UTC
