### ISSUE TITLE
Incorrect working with environment variables (using dotenv and babel plugin)

### ISSUE THREAD

**Issue by siarheipashkevich** [expo/router#533] opened 2023-05-02 10:36 UTC
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Hi all,

I want to use env variables in my app using dotenv package and https://docs.expo.dev/guides/environment-variables/#using-babel-to-inline-environment-variables-during-build-time for using env variables in my app.

But when I building my app I'm getting en error:

iOS:
![image](https://user-images.githubusercontent.com/7753600/235643773-43fa0f42-c761-4ad0-af1d-fe8bd291f74d.png)

Android:
![image](https://user-images.githubusercontent.com/7753600/235644051-3630dbda-7ef6-4385-9746-9bbfeb86182e.png)

Is it possible to use dotenv package and babel plugin in `expo-router`?

### Minimal reproducible example

1. create new app with `expo-router`
2. add `dotenv` package and babel plugin (see here https://docs.expo.dev/guides/environment-variables)
3. build app: `eas build -e preview`

**Comment by siarheipashkevich** [comment] 2023-05-17 09:56
@EvanBacon could you please check this issue, maybe `expo-router` is not working with `dotenv` correctly using `eas` ?

**Comment by marcel099** [comment] 2023-05-22 00:26
Hello, Sergey.

I recently faced a similar issue when I tried to use Expo Router and environment variables on the same project. I first used [`babel-plugin-inline-dotenv`](https://www.npmjs.com/package/babel-plugin-inline-dotenv) on my application, but it stopped working after I added _Expo Router_ to it. Then I tried [`react-native-dotenv`](https://www.npmjs.com/package/react-native-dotenv). Fortunately, it worked with _Expo Router_. I don't know if `eas` works with `react-native-dotenv`, but I hope this report can help you.

**Comment by oliviercperrier** [comment] 2023-06-20 06:59
I use dotenv and it work great on ios and android but when lauching the web application, the environment variables are not loaded... Any idea?

**Comment by siarheipashkevich** [comment] 2023-06-20 08:01
In my case I have problems using `eas`

**Comment by EvanBacon** [comment] 2023-07-14 06:08
The issue is probably that the third-party env var libraries are removing the requisite environment variables used to configure Expo Router from Expo CLI. I recommend moving to the new [built-in environment variables](https://docs.expo.dev/guides/environment-variables/) which I added for solving this issue.

You can alternatively "blocklist" the required environment variables, these are currently:

- EXPO_ROUTER_ABS_APP_ROOT
- EXPO_ROUTER_APP_ROOT
- EXPO_ROUTER_IMPORT_MODE_WEB
- EXPO_ROUTER_IMPORT_MODE_IOS
- EXPO_ROUTER_IMPORT_MODE_ANDROID
- EXPO_ROUTER_IMPORT_MODE

**Closed by EvanBacon** 2023-07-14 06:08 UTC
