### ISSUE TITLE
Status Bar in _layout has no effect

### ISSUE THREAD

**Issue by andrew-levy** [expo/router#754] opened 2023-07-08 04:37 UTC
### Which package manager are you using? (Yarn is recommended)

Yarn

### Summary

Adding a `StatusBar` component from `expo-status-bar` in a layout file has no effect on the status bar. Works as expected on SDK 48, v1 but not in SDK 49, v2 which leads me to believe this may be a bug with layout routes. 

I put a console.log in the expo status bar library and it seems to set the correct status bar color, but then quickly rerenders with the dark value, causing it to have no effect. Not sure where that second rerender is coming from, possibly related to some of the other issues? 

Using:
SDK 49
Expo Router v2
Expo Status Bar 1.6.0

### Minimal reproducible example

``` tsx 
import { Stack } from "expo-router";
import { StatusBar } from "expo-status-bar";

export default function RootLayout() {
  return (
    <>
      <StatusBar style={"light"} />
      <Stack />
    </>
  );
}
```

**Comment by louislatreille** [comment] 2023-07-13 15:35
I'm having the same issue using the same versions.

**Comment by louislatreille** [comment] 2023-07-23 16:57
Additional information: It seems to be happening on Android only. iOS seems to be working fine.

**Comment by andrew-levy** [comment] 2023-07-23 17:16
I originally had the issue on ios, but i'll check again and see if it's still an issue

**Comment by corasan** [comment] 2023-07-26 06:53
This is an issue for me as well on iOS. Only works when using StatusBar on each screen individually.

**Comment by louislatreille** [comment] 2023-07-27 20:23
Haven't done anything to make it work on iOS.

To give more context, I've migrated from react-navigation to expo-router lately. I haven't changed anything to the status bar theme that I had before. I.e. I have the StatusBar component in one of my top level component.

**Comment by louislatreille** [comment] 2023-07-27 21:13
I've done a bit more investigation, and it seems that what is overriding the status bar style is this: https://github.com/expo/router/blob/f69e31c84a83ceb6d678dfb8aeed708974d301a8/packages/expo-router/src/ExpoRoot.tsx#L74

```
{/* Users can override this by adding another StatusBar element anywhere higher in the component tree. */}
{!hasViewControllerBasedStatusBarAppearance && (
  <StatusBar style="auto" />
)}
```

If I remove the `StatusBar` component from there in my node_modules, my style is applied properly.

It is unclear to me what the comment there means. From my understanding, the ExpoRoot component is the top most component of the application. There's nothing in my app that is higher than that. Perhaps the entry file was set differently in expo-router v1?

It is also unclear to me if expo-router should be setting the status bar style at all. Although, there definitely could be a good reason that I am not aware of.

**Comment by dserranog1** [comment] 2023-08-17 03:25
I was having the same issue, no matter what `style` I set to my `StatusBar` in my `_layout` component the `StatusBar` was using the corresponding `style` based on what theme was set by iOS (which in my case was dark, so `StatusBar` was always `light`), this might be a bug. I found a workaround by explicitly setting the `userInterfaceStyle` to `light` in my `app.json` as explained [here](https://docs.expo.dev/develop/user-interface/color-themes/). After this, setting the `StatusBar` `style` worked fine.

**Comment by zackify** [comment] 2023-08-30 23:21
@EvanBacon can we get this merged. i guess for now we can patch package the line, thanks @louislatreille

**Comment by Azanniel** [comment] 2023-10-06 12:59
Not only is it affecting the stylization but also the "translucent" property. In my case it is not becoming translucent.

**Comment by Azanniel** [comment] 2023-10-06 14:07
In an excerpt from the file `expo-router/src/views/Navigator.tsx`

Instead of using `SafeAreaView` I added a View:

```tsx
export function DefaultNavigator() {
  return (
    <View style={{ flex: 1 }}>
      <Navigator>
        <QualifiedSlot />
      </Navigator>
    </View>
  );
}
```

With this, the StatusBar worked with the translucent property:

```tsx
export default function Page() {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'center',
      }}
    >
      <Text>Hello world from route based file</Text>

      <StatusBar
        style="dark"
        backgroundColor="transparent"
        translucent={true}
      />
    </View>
  )
}
```

I just made a small correction, but I don't have enough knowledge to implement this efficiently.
I wanted to leave my contribution here by discovering the problem in question.

If I'm mistaken about the purpose of the current implementation, please help me understand 😅

**Comment by Taraslysak** [comment] 2024-03-02 08:18
This issue re-appeared in expo-router v3, expo SDK 50 on android devices (Samsung A21 specifically). When StatusBar is declared in `_layout.ts` files it is ignored and now there apparently is no `node_modules/expo-router/src/ExpoRoot.tsx` to make the fix

**Comment by zackify** [comment] 2024-03-02 13:36
Here’s the patch I’m using in v3. 

diff --git a/node_modules/expo-router/build/ExpoRoot.js b/node_modules/expo-router/build/ExpoRoot.js
index 7db529d..47908f9 100644
--- a/node_modules/expo-router/build/ExpoRoot.js
+++ b/node_modules/expo-router/build/ExpoRoot.js
@@ -57,7 +57,7 @@ function ExpoRoot({ wrapper: ParentWrapper = react_1.Fragment, ...props }) {
         initialMetrics={INITIAL_METRICS}>
           {children}
           {/* Users can override this by adding another StatusBar element anywhere higher in the component tree. */}
-          {!hasViewControllerBasedStatusBarAppearance && <expo_status_bar_1.StatusBar style="auto"/>}
+          {/* {!hasViewControllerBasedStatusBarAppearance && <expo_status_bar_1.StatusBar style="auto"/>} */}
         </react_native_safe_area_context_1.SafeAreaProvider>
       </ParentWrapper>);
     };

**Comment by arasrezaei** [comment] 2024-03-05 19:38
same here

**Comment by marklawlor** [comment] 2024-03-06 01:01
This should be resolved in v3. 

If you are still having this issue, please create a new issue in the main repo https://github.com/expo/expo with a reproduction of your issue and information on what devices you are testing on.

You should not need to patch Expo Router. Please demonstrate what you are trying to achieve so we can either provide assistance or implement a fix. 

This repo (and v2) is in maintenance mode. I'm closing this issue as this is fixed in v3 and does not warrant a backport to v2.

**Closed by marklawlor** 2024-03-06 01:01 UTC

**Comment by vitorcamachoo** [comment] 2024-03-19 15:53
Still have this issue on v3. [This fixed](https://github.com/expo/router/issues/754#issuecomment-1681553744) my problem, although is a temporary solution.

**Comment by MariuzM** [comment] 2024-03-20 16:41
This is still an issue with latest expo now :(

**Comment by arasrezaei** [comment] 2024-03-20 16:43
Yes I used

> Here’s the patch I’m using in v3.
> 
> diff --git a/node_modules/expo-router/build/ExpoRoot.js b/node_modules/expo-router/build/ExpoRoot.js index 7db529d..47908f9 100644 --- a/node_modules/expo-router/build/ExpoRoot.js +++ b/node_modules/expo-router/build/ExpoRoot.js @@ -57,7 +57,7 @@ function ExpoRoot({ wrapper: ParentWrapper = react_1.Fragment, ...props }) { initialMetrics={INITIAL_METRICS}> {children} {/* Users can override this by adding another StatusBar element anywhere higher in the component tree. */}
> 
> * ```
>        {!hasViewControllerBasedStatusBarAppearance && <expo_status_bar_1.StatusBar style="auto"/>}
>   ```
> 
> * ```
>        {/* {!hasViewControllerBasedStatusBarAppearance && <expo_status_bar_1.StatusBar style="auto"/>} */}
>      </react_native_safe_area_context_1.SafeAreaProvider>
>    </ParentWrapper>);
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   };

Yes it's still an issue on android.
I used this patch to fix it

**Comment by MariuzM** [comment] 2024-03-20 16:44
im on iOS and having this issue

**Comment by dylancom** [comment] 2024-03-20 17:02
As the package moved I think it should be reported here: https://github.com/expo/expo/

**Comment by jatinhemnani01** [comment] 2024-03-23 07:22
facing the same problem, how do I fix it?

**Comment by marjus15** [comment] 2024-03-31 12:01
> I've done a bit more investigation, and it seems that what is overriding the status bar style is this:
> 
> https://github.com/expo/router/blob/f69e31c84a83ceb6d678dfb8aeed708974d301a8/packages/expo-router/src/ExpoRoot.tsx#L74
> 
> ```
> {/* Users can override this by adding another StatusBar element anywhere higher in the component tree. */}
> {!hasViewControllerBasedStatusBarAppearance && (
>   <StatusBar style="auto" />
> )}
> ```
> 
> If I remove the `StatusBar` component from there in my node_modules, my style is applied properly.
> 
> It is unclear to me what the comment there means. From my understanding, the ExpoRoot component is the top most component of the application. There's nothing in my app that is higher than that. Perhaps the entry file was set differently in expo-router v1?
> 
> It is also unclear to me if expo-router should be setting the status bar style at all. Although, there definitely could be a good reason that I am not aware of.

This worked for me thank you

**Comment by karanmartian** [comment] 2024-04-01 11:15
this is happening even with React Navigation 5.x and Expo SDK 49/50. if i use Navigation 6.x it works

**Comment by 0horaa** [comment] 2024-04-01 19:03
same here

**Comment by julian-gargicevich** [comment] 2024-04-02 03:03
Same issue

**Comment by karanmartian** [comment] 2024-04-02 03:12
Please fix this issue asap, as I want to use React Navigation 5.x with SDK 50. I am seeing some white blank screen after splash screen momentarily when i use 6.x with SDK 50 but it used to work much smoother which 5.x and sdk 48. so if you can just make 5.x and sdk 50 work together so that this issue is not found with this combination.

**Comment by marklawlor** [comment] 2024-04-05 00:26
This repo is in maintenance mode and not monitored for support issues. If your having an issue, please report on the main report https://github.com/expo/expo/. 

@karanmartian SDK 50 supports `@react-navigation/native`: ^6.0.2`. You free to use 5.x, but we will not prioritise fixing issues for unsupported versions outside the SDK version range. There are typically breaking changes between major versions that make backwards compatibility very difficult.

**Comment by marklawlor** [comment] 2024-04-05 02:42
Like I said earlier, this repo is in maintenance mode and we are not monitoring support issues here. This is not the place to ask that question. Please create an issue at https://github.com/expo/expo/ and follow the issue template.

I can only provide very limited assistance without a minimal reproduction of the problem. This is not a reported problem I'm aware of, so I can't provide assistance without you providing more information.

**Comment by denzelcurry95** [comment] 2024-06-13 07:27
Hey there,

we have a workaround for styling the status bar in _layout, it looks like this:

```
import {NativeModules, processColor} from 'react-native';
import {useEffect} from "react";
const { StatusBarManager } = NativeModules;

export default function Root() {
  useEffect(() => {
    StatusBarManager.setColor(processColor("#000000"), false);
    StatusBarManager.setStyle("light-content");
  }, []);

...
(other code)
...
```

**Comment by mathura333** [comment] 2024-07-10 09:31
Looks like this issue is still there

**Comment by mathura333** [comment] 2024-07-10 09:31
> Hey there,
> 
> we have a workaround for styling the status bar in _layout, it looks like this:
> 
> ```
> import {NativeModules, processColor} from 'react-native';
> import {useEffect} from "react";
> const { StatusBarManager } = NativeModules;
> 
> export default function Root() {
>   useEffect(() => {
>     StatusBarManager.setColor(processColor("#000000"), false);
>     StatusBarManager.setStyle("light-content");
>   }, []);
> 
> ...
> (other code)
> ...
> ```

This did not work for me

**Comment by mathura333** [comment] 2024-07-10 09:42
**Solution**
Did this hack and it worked for me

```
import { useEffect } from 'react';
import { Slot, usePathname } from 'expo-router';
import { StatusBar } from 'react-native';

const Layout = () => {
  const pathname = usePathname();

  useEffect(() => {
    setTimeout(() => {
      StatusBar.setBarStyle('light-content');
    }, 0);
  }, [pathname]);

  return (
    <>
      <StatusBar barStyle="light-content" />

      <Slot />
    </>
   );
};

export default Layout;

```

**Comment by JoelSoy** [comment] 2024-08-30 04:33
This is my solution:
I think that when using "<StatusBar/>" and then "<Stack/>" Stack overwrites its own values ​​making "<StatusBar/>" obsolete:
<Stack
screenOptions={{
headerStyle: { backgroundColor: "black" },
statusBarStyle: "light",
statusBarColor: "black",

I recommend customizing this for each page:
<Screen>
<Stack.Screen
options={{
headerStyle: { backgroundColor: "#ffee00" },
headerTintColor: "black",
statusBarStyle: "dark",

**Comment by JoelSoy** [comment] 2024-08-30 04:34
**### This is my solution:**
I think that when using `<StatusBar/>` and then `<Stack/>` Stack overwrites its own values ​​making `<StatusBar/>` obsolete:

```javascript
<Stack
        screenOptions={{
          statusBarColor: "#0B0B0B", //backgroundColor for Statusbar
          statusBarStyle: "light",  //color for elements the icons
        }}
      />
``` 
 I **recommend customizing** this for each page:
  
```javascript
<Screen>
      <Stack.Screen
        options={{
          headerStyle: { backgroundColor: "#ffee00" },
          headerTintColor: "black",
          statusBarStyle: "dark",
```

**Comment by PetrusBorges** [comment] 2024-09-16 19:48
> **Solution** Did this hack and it worked for me
> 
> ```
> import { useEffect } from 'react';
> import { Slot, usePathname } from 'expo-router';
> import { StatusBar } from 'react-native';
> 
> const Layout = () => {
>   const pathname = usePathname();
> 
>   useEffect(() => {
>     setTimeout(() => {
>       StatusBar.setBarStyle('light-content');
>     }, 0);
>   }, [pathname]);
> 
>   return (
>     <>
>       <StatusBar barStyle="light-content" />
> 
>       <Slot />
>     </>
>    );
> };
> 
> export default Layout;
> ```

this works for me, is unbelivable that we need to put this quick fix to statusbar work ok

**Comment by bitsmanent** [comment] 2024-09-24 14:27
@JoelSoy That worked. Thanks!

**Comment by harmony-netizen** [comment] 2024-10-05 07:48
This one works for me on android, thanks so much @JoelSoy ! 
But on iOS seems to cause an issue :

```
If you want to change the appearance of status bar, you have to change
UIViewControllerBasedStatusBarAppearance key in the Info.plist to YES

RNScreens::RNScreensTurboModule::getPropertyNames(facebook::jsi::Runtime&)
```
Seems for iOS, I need to use `userInterfaceStyle` in `app.json`


> **### This is my solution:** I think that when using `<StatusBar/>` and then `<Stack/>` Stack overwrites its own values ​​making `<StatusBar/>` obsolete:
> 
> ```js
> <Stack
>         screenOptions={{
>           statusBarColor: "#0B0B0B", //backgroundColor for Statusbar
>           statusBarStyle: "light",  //color for elements the icons
>         }}
>       />
> ```
> 
> I **recommend customizing** this for each page:
> 
> ```js
> <Screen>
>       <Stack.Screen
>         options={{
>           headerStyle: { backgroundColor: "#ffee00" },
>           headerTintColor: "black",
>           statusBarStyle: "dark",
> ```

**Comment by karlhorky** [comment] 2024-11-06 14:37
The `<StatusBar>` component can be used again starting in [Expo Router v4.0.0-preview.0](https://github.com/expo/expo/blob/main/packages/expo-router/CHANGELOG.md#400-preview0--2024-10-22) 🎉

> - Render the default StatusBar before screens are rendered. (https://github.com/expo/expo/pull/31624 by [@marklawlor](https://github.com/marklawlor))

References:

- https://github.com/expo/expo/issues/30497
- https://github.com/expo/expo/pull/31624
