### ISSUE TITLE
Navigation between screens not working in Android APK

### ISSUE THREAD

**Issue by rafinharfc93** [expo/router#729] opened 2023-07-05 04:05 UTC
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

Hello friends.

While running the application in Expo GO, all navigation between screens works perfectly using the `router.push` function, but whenever I generate an apk to test the application, this navigation does not work, I notice that there is a click because where I click gives the effect of opacity, but nothing happens.

I have a branch prior to an `npx expo prebuild` where this error does not occur, but if I run `npx expo prebuild `again so that expo reads the app.json file again, this error occurs again.

### Minimal reproducible example

```
<TouchableHighlight
          className="mr-5"
          key={index}
          onPress={() => {
            router.push(`/${screenRoute}?ID=${item.ID}`);
          }}
        >
          <ExpoFastImage
            uri={item.poster}
            style={{ width: 150, height: 200 }}
            cacheKey={item.ID}
          />
        </TouchableHighlight>
```

**Comment by marklawlor** [comment] 2023-07-18 03:00
Can you please provide a full minimal reproducible example.

**Comment by EvanBacon** [comment] 2023-12-14 19:02
Closing as we cannot reproduce this issue.

**Closed by EvanBacon** 2023-12-14 19:02 UTC
