### ISSUE TITLE
The action 'NAVIGATE' with payload {"name":"StartScreen"} was not handled by any navigator.

### ISSUE THREAD

**Issue by kishieel** [expo/router#792] opened 2023-07-17 15:34 UTC
### Which package manager are you using? (Yarn is recommended)

yarn

### Summary

When I am trying to redirect to '/(flows)/StartScreen' I got an error same as in title. Project structure looks like below. Am I missing something with this structure or in expo-router all  screens have to be in app directory (though tabs work  when they are nested)? 

Tabs and screens in app directory work as expected. Only screens in (flows) directory seem to be problematic.

PS. I  also noticed when I use `router.push('asdasdasdasd')` it redirects me to [...missing].tsx, but when I am using StartScreen there is only error. Why?

### Minimal reproducible example

Project structure

```
app/
    (lobby)/ <-- tab layout
        _layout.tsx
        a.tsx
        b.tsx
    (flows)/
        _layout.tsx
        StartScreen.tsx
        EndScreen.tsx
    _layout.tsx
    [...missing].tsx
    Info.tsx
```

app/_layout.tsx
```tsx
        <>
            <Stack initialRouteName="(lobby)">
                <Stack.Screen name="(lobby)" options={{ headerShown: false }} />
                <Stack.Screen name="(flows)" options={{ headerShown: false }} />
            </Stack>
        </>
```

app/(flows)/_layout.tsx
```
import { Stack } from 'expo-router';
export default Stack;
}
```

app/(flows)/StartScreen.tsx
```
export default function StartScreen() {
    return (
        <>
            <Stack.Screen name={StartScreen.name} />
            <View>
                <Text style={{ color: Colors.white }}>Start screen</Text>
            </View>
        </>
    );
}
```

**Comment by jsp3536** [comment] 2023-07-17 18:27
I have a similar layout that was previously working for me with expo-router v1.5 but now that I am using expo-router v2 and Expo SDK 49 I see the same error as you

**Comment by marklawlor** [comment] 2023-07-18 01:36
Please provide a full reproduction (the simplest method is sharing a Github repo). Your description does not match the reproduction provided.

**Comment by marklawlor** [comment] 2023-07-18 01:57
Re-reading again. I believe the issue is caused by this bug https://github.com/expo/router/issues/793

I'm going to close this issue in favour of that issue, but feel free to reply if I'm wrong and I can reopen

**Closed by marklawlor** 2023-07-18 01:57 UTC

**Comment by kishieel** [comment] 2023-07-18 07:54
> Please provide a full reproduction (the simplest method is sharing a Github repo). Your description does not match the reproduction provided.

@marklawlor here is a repo that can be used to reproduce this error https://github.com/kishieel/expo-router-2-bug-repro

Also, not sure if this is worth to mention, but everything in this repo work when I downgrade expo packages to:

```
    "expo": "~48.0.18",
    "expo-font": "~11.1.1",
    "expo-linking": "~4.0.1",
    "expo-router": "^1.5.3",
    "expo-splash-screen": "~0.18.2",
    "expo-status-bar": "~1.4.4",
    "expo-system-ui": "~2.2.1",
    "expo-web-browser": "~12.1.1",
```

**Comment by devoren** [comment] 2023-07-21 16:25
same issue, from tabs i can't push or replace to another stack
