### ISSUE TITLE
my app is working good, but have icons issue on web

### ISSUE THREAD

**Issue by AhmedrAshraf** [expo/router#543] opened 2023-05-05 08:48 UTC
### Which package manager are you using? (Yarn is recommended)

None

### Summary

my app is working well, but I have an icons issue on the web, when I try to run it on the web it gives me some errors in icons, I solved that error but my vector icons are not showing, can anyone confirm please that the vector icons are working on a web or not?

### Minimal reproducible example

try to use vector icon in app and try running on web.

**Comment by marklawlor** [comment] 2023-05-08 05:29
I'm going to close this issue due to a lack of information.

If you are have an issue with a particular icon library, I would recommend creating in issue in that libraries' repo. Otherwise consider sharing with us your minimal reproduction of your issue so we could assist your further.

**Closed by marklawlor** 2023-05-08 05:29 UTC
