### ISSUE TITLE
@radix-ui/react-slot error

### ISSUE THREAD

**Issue by bndkt** [expo/router#621] opened 2023-06-02 00:42 UTC
### Which package manager are you using? (Yarn is recommended)

npm

### Summary

Just in case anyone encounters the error

> Unable to resolve "@radix-ui/react-slot" from "node_modules/expo-router/src/link/Link.tsx"

It seems to be a problem with version 1.0.2 of @radix-ui/react-slot. Expo Router defines the dependency as `"@radix-ui/react-slot": "^1.0.0"`. @EvanBacon maybe for now it makes sense to pin down the version to "1.0.1" strictly?

For now you can use "overrides" in package.json to fix the @radix-ui/react-slot version.

### Minimal reproducible example

https://github.com/bndkt/expo-mre

**Comment by rborn** [comment] 2023-06-05 19:56
I can confirm I get this too

**Comment by marklawlor** [comment] 2023-06-05 22:50
I cannot reproduce it with the repo provided.

Steps performed:
 - Cloned repo
 - Removed `overrides` from package.json =
 - Changed `expo` version to be `48.0.19` (49 is still in alpha and not released)
 - npx expo
 - Ran in android emulator and on web.

The error you are receiving suggests that the issue is different than what you are reporting. `Unable to resolve` is a resolution error and occurs when the package was unable to be located within in the Metro module resolution paths. I would suggest checking your dependancies within node_modules and if you are customising the Metro resolution paths (e.g. you have a monorepo) ensuring that the paths are correct.

I'm going to close this issue for now, but you are welcome to respond with more information and we can reopen once the issue has been isolated.

**Closed by marklawlor** 2023-06-05 22:50 UTC

**Comment by EvanBacon** [comment] 2023-07-14 19:10
We fixed this by pinning the version as suggested. Next time I recommend opening a PR instead 👍
