### ISSUE TITLE
Unable to resolve module expo-router/entry

### ISSUE THREAD

**Issue by META-DREAMER** [expo/router#67] opened 2022-10-07 22:58 UTC
Getting the following error while bundling for iOS simulator. Using pnpm.

```
Unable to resolve module expo-router/entry from <root>/apps/expo/index.js: expo-router/entry could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  node_modules
  ../../node_modules
> 1 | import "expo-router/entry"
    |         ^
  2 |
```

package.json:
```
"dependencies": {
    "app": "workspace:*",
    "expo": "46.0.15",
    "expo-router": "^0.0.25",
    "expo-splash-screen": "~0.16.1",
    "expo-status-bar": "~1.4.0",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-native": "0.69.6",
    "react-native-gesture-handler": "~2.5.0",
    "react-native-reanimated": "~2.9.1",
    "react-native-safe-area-context": "4.3.1",
    "react-native-screens": "~3.15.0",
    "react-native-web": "~0.18.7"
  },
  "devDependencies": {
    "@babel/core": "^7.18.6",
    "@babel/runtime": "^7.18.6",
    "@types/react": "~18.0.0",
    "@types/react-native": "~0.69.1",
    "typescript": "^4.6.3"
  }
```
babel.config.js, metro.config.js and index.js:
![CleanShot 2022-10-07 at 17 15 31](https://user-images.githubusercontent.com/7143583/194674310-d661f7fa-25a7-470d-a10c-f41a1c6ad8e1.png)

**Comment by EvanBacon** [comment] 2022-10-10 18:19
Not enough details, need a repro. I imagine this is a duplicate of https://github.com/expo/router/issues/29

**Closed** 2022-10-12 03:51 UTC

**Comment by eivindml** [comment] 2022-10-21 06:52
@META-DREAMER Did you figure out what was wrong? I have the same issue with `pnpm`, and it's not a duplicate of #29.
