### ISSUE TITLE
router.push error saying "The action 'NAVIGATE' with payload {"name":"sign-in"} was not handled by any navigator"

### ISSUE THREAD

**Issue by SophieJung7** [expo/router#510] opened 2023-04-21 11:45 UTC
### Summary

I used router.push function from expo-router and this function provokes error. 

### Minimal reproducible example

![image](https://user-images.githubusercontent.com/36703871/233626707-8e8fea14-0e9b-4c32-9dd8-217b33bc325b.png)

_layout.tsx
```javascript
import {Stack} from 'expo-router';

export default function AuthLayout() {
  return <Stack screenOptions={{headerShown: false}} />;
}
```
loading.tsx
```javascript
 useEffect(() => {
    if (!auth.currentUser && !isLoading) {
      router.push('/sign-in');
    }
   
  }, [isLoading, router]);
```

This useEffect hook at loading.tsx gives an error of "The action 'NAVIGATE' with payload {"name":"sign-in"} was not handled by any navigator."

![image](https://user-images.githubusercontent.com/36703871/233627227-f322a369-db01-4b7f-8698-92986d7d52c4.png)

I tried both '/(auth)' , '/(auth)/sign-in' but same error appears.

**Comment by WKampel** [comment] 2023-04-24 07:28
Did you ever figure this out?

**Comment by WKampel** [comment] 2023-04-24 09:02
For me, this appears to only happen during replace (push works).

**Comment by mohrizshahid** [comment] 2023-04-25 08:58
try  '(auth)/sign-in' this. may be it solved your issue

**Comment by WKampel** [comment] 2023-04-27 13:11
That did not solve it for me.

**Comment by mohrizshahid** [comment] 2023-04-27 17:08
Have you tried without first / as i have written

**Comment by SophieJung7** [comment] 2023-05-04 14:16
@mohrizshahid  '(auth)/sign-in' did not solve the error and also that route is against documentation. please read expo router documentation.

**Comment by Drakeoon** [comment] 2023-05-30 21:35
I can confirm I have the same issue in my case. `push` works properly, whereas `replace` throws very similar error. My rough guess would be that it's related to having more than 1 "group segment"

| Both `replace` and `push` working | `replace` not working, `push` working |
| --- | --- |
| <img width="322" alt="CleanShot 2023-05-30 at 23 30 58@2x" src="https://github.com/expo/router/assets/24693481/653a76e0-acfa-4c53-bd44-6730c0822a58"> | <img width="333" alt="CleanShot 2023-05-30 at 23 34 15@2x" src="https://github.com/expo/router/assets/24693481/c5b3b231-1eef-47e6-a9d0-0103ab834c5f"> |

The route that i'm trying access exists in `(authenticated)` group, but does not exist in `(guest)`. It must be doing some kind of a lookup inside `(guest)`, not finding it, then throwing an error before trying further

**Comment by glitchassassin** [comment] 2023-05-31 00:46
I'm seeing a similar issue, and for some reason removing `_layout.tsx` in the target group causes the route to be loaded successfully.

**Comment by glitchassassin** [comment] 2023-05-31 14:15
Seems to be related to this PR:

https://github.com/expo/router/pull/532

the author says:

> This PR makes the assumption that targetState will always have a routes key with a single route, which I think is correct?

however, in my case this is not correct - we have initialRouteName set in a parent _layout.tsx and so the routes key looks like this:

```
"routes": [{"name": "index"}, {"_route": undefined, "name": "(no auth)", "state": [Object]}]
```

Previously `isMovingToSiblingRoute` took the last route in the list, but the PR changed to taking the first route, which has no state.

Getting rid of the initialRouteName in our layout solved the above error, but now the screen is rerendering over and over again. Troubleshooting further...

**Comment by glitchassassin** [comment] 2023-05-31 15:00
Should note that our folder structure looks like this:

```
app/
  (auth)/
    log-in.tsx
  (no auth)/
    _layout.tsx
    device-not-configured.tsx
  _layout.tsx
```

The nested app/(no auth)/_layout.tsx seems to be triggering the issues - if we remove it, so we only have a single layout, it works fine.

**Comment by dherault** [comment] 2023-06-06 07:06
Same error with a `reset` action: `The action 'Navigation/RESET' was not handled by any navigator.`

**Comment by JClackett** [comment] 2023-06-06 14:34
Also facing this exact same issue

**Comment by felipevc13** [comment] 2023-06-23 12:37
I have the same problem, on my login screen I do a redirect to router.replace("/(tabs)/agenda");

and I have the error 
"The action 'REPLACE' with payload {"name":"agenda"} was not handled by any navigator.

Do you have a screen named 'agenda'?"

My folder structure is:

app/
  (tabs)/
    _layout.js
     agenda.js
     servicos.js
 _layout.tsx
 index.js
 login.js

**Comment by marklawlor** [comment] 2023-07-18 02:54
Closing in favour of https://github.com/expo/router/issues/793

**Closed by marklawlor** 2023-07-18 02:54 UTC

**Comment by louisambrose98** [comment] 2023-08-07 17:34
I fixed this issue by changing the initialRouteName.

Default is (tabs). Now it is  (auth) in app/_layout.tsx 

```
export const unstable_settings = {
  // Ensure that reloading on `/modal` keeps a back button present.
  initialRouteName: "(auth)",
};
```
